version: '3'
services:
  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "3001:80"
    restart: always

  backend:
    build: ./server
    container_name: backend
    ports:
      - "5001:9000"
    restart: always
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
