version: '3'
services:
  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "3001:80"  # production ke liye 80 port rakho
    restart: always

  backend:
    build: ./server
    container_name: backend
    ports:
      - "5001:5001"
    restart: always
    env_file:
      - ./server/.env
    depends_on:
      - frontend
