name: Deploy to EC2

on:
  push:
    branches:
      - main  # Or whatever your main branch is

jobs:
  deploy:
    name: Deploy App on EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy over SSH to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2HOST }}
          username: ubuntu
          key: ${{ secrets.EC2KEY }}
          script: |
            cd /var/www/html/Books
            git pull origin main
            docker compose down
            docker compose up -d --build
